### ISSUE TITLE
Thanks for choosing CMake.js

### ISSUE THREAD

**Issue by unbornchikken** [dasantonym/node-wdt-native#1]
Hi there,

Since you're the author of the first module which is using CMake.js, I can offer you exclusive support. I mean CMake.js were tested by only by me and my friends with as many synthetic use cases as we coluld imagine on as many platforms those we could reach, but it's still in needing real world stress use to bring up its hidden issues.

So if you're having any real world issues related to CMake.js I'm gonna threat them on high prio. 

BR,
unbornchikken

**Comment by unbornchikken** [comment]
However I noticed something in your readme that is misleading. 

"It automatically builds for node-webkit version 0.12.1 (see package.json if you want to build for nodejs)."

That's now how CMake.js really work. A module doesn't decide which runtime it will actually used against. An application developer decide. So, if an application get designed by using your module, then it have to specify cmake-js setting in its package.json (= root package.json), to setup the actual nw.js version that it uses. 

As a module developer you don't have to think about your module uses, that's CMake.js job. So you dont have to specify anything in module's package file, just add a mention in your readme about that it's required to specify cmake-js setting in an application that uses your module.

Actually defining cmake-js key in your module's package.json file leads to an error. Why? If you set it up to use nw.js 0.12.1 for example, then when it gets compiled during development time (to run its unit tests for example) it's gonna be compiled against io.js 1.2 runtime. But if you're having io.js 34.0.1 then, which is binary incompatible with 1.2, then your unit tests will fail. So it is advised to not use cmake-js target settings in your module's package.json, because that way CMake.js will use that you have, and your tests will pass.

I hope that is clear.

**Comment by dasantonym** [comment]
hey man, thanks for the kind feedback and the support offer! and even more thanks for the hint on the compile settings. i really didn't get that one right and have updated the module and the project that uses it.

i am in the process of writing a second one with cmake-js right now and i really like it so far. will be reporting back should i run into any more issues. great project!
